import argparse
from qwen.model import QWENModel
from tqdm import tqdm


def main(args):
    
    llm = QWENModel()
    system_prompt = f"""You are an AI assistant that classifies a decision based on textual analysis. You will be given a paragraph of text generated by another AI, which evaluates whether two images show the same person.

        Your job is to:
        1. Carefully read the text.
        2. Identify the final decision made in the text — whether the two images are of the *same person* or *different people*.
        3. Output ONLY one of the following:
        - 0 → if the final conclusion is SAME PERSON.
        - 1 → if the final conclusion is DIFFERENT PERSON.

        You must respond with exactly one character: either 0 or 1. Do not include any explanation, comments, words, or punctuation — only the number."""
    
    
    with open(args.response_path, "r") as f:
        responses = [line.strip() for line in f.readlines()]
    
    output_path = args.response_path.replace(".txt", "_processed.txt")
    
    
    
    with open(output_path, "w") as f:
        for i in tqdm(range(0, len(responses), args.batch_size)):
            batch_response = responses[i:i + args.batch_size]

            output_llm = llm.inference(prompts=batch_response, 
                                       system_prompt=system_prompt)

            for out in output_llm:
                f.write(f"{out}\n")
        

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--response_path", type=str, default="")
    parser.add_argument("--batch_size", type=int, default="8")
    args = parser.parse_args()
    main(args)